### ISSUE TITLE
Restart Interrupted by Self Service

### ISSUE THREAD

**Issue by manicslothpdx** [kc9wwh/macOSUpgrade#135] opened 2019-12-11 04:52 UTC
We've been using this script for years, but during my initial Mojave->Catalina tests, the process will not auto-close the Self Service policy window. We have to close the policy description window manually, and then Self Service will quit on its own, allow the install to continue. Otherwise, the process gets stuck at a popup stating Self Service interrupted the restart. As far as I can tell, this is a new issue for us.

**Comment by jrouthier** [comment] 2019-12-11 13:13
I also just noticed this yesterday while performing a High Sierra to Mojave upgrade, and then subsequently using the script to erase the now upgraded to Mojave computer. Currently using version 2.7.2.2 for upgrade and erase.

**Comment by ckostovny** [comment] 2019-12-11 17:57
I also noticed this starting this week, I think. I was upgraded to Jamf Pro 10.17.1 over the weekend, were either of you? I had not changed my macOSUpgrade script before I started to notice the "Self Service interrupted restart" messages.

**Comment by jrouthier** [comment] 2019-12-11 18:00
We are cloud hosted, so our instance was upgraded to 10.17.1 this weekend as well.

**Comment by manicslothpdx** [comment] 2019-12-11 19:36
We upgraded our JSS to 10.17.1 over the weekend as well.

**Comment by Coros** [comment] 2019-12-12 16:53
The catalina installer has a new switch to forcequitapps. ("--forcequitapps")  It would be nice for this to be added as an option to the script by default.

You can customize the "startosinstallOptions" array to look like: `startosinstallOptions+=(
"--agreetolicense"
"--nointeraction"
"--forcequitapps"
)`

This should make it function.

**Comment by ckostovny** [comment] 2019-12-12 19:27
I did try adding "--forcequitapps" to the startosinstallOptions array for installer major verision greater or equal to 15, and it does appear to resolve this self service issue with restarting. Not sure if the switch causes issues with older macOS installers, so I wanted to make sure I was only applying for Catalina or newer.

**Comment by sintichn** [comment] 2019-12-13 17:45
I'm having the same issue, just upgraded our JSS to 10.17.1 yesterday. We have folks going from sierra to Mojave. I know the --forcequitapps flag doesn't work for the Mojave installer. Has anyone found a workaround?

**Comment by myoaungchit** [comment] 2019-12-18 02:54
I'm having the same issue while doing implementing Mojave upgrade from High Sierra or lower. Our JSS instance's cloud based, so it was auto updated to 10.17.1 as well. Hoping that there'll be a workaround.

**Comment by sintichn** [comment] 2019-12-18 14:17
I ended up adding `killall Self\ Service` right before ##Load LaunchAgent on line 491 of the original script and that did the trick. I was testing it and saw it close self service right before it launched the full screen "Please wait as we upgrade your computer".

**Comment by jrouthier** [comment] 2019-12-18 21:12
Thank you @sintichn . I can confirm that adding that line allows for both an upgrade from High Sierra to Mojave, as well as using the script to Erase a Mojave machine.

**Comment by myoaungchit** [comment] 2019-12-19 08:06
Thank you @sintichn too. Adding the killall command at Line 491 to the script does solve the issue.

**Comment by jrouthier** [comment] 2019-12-20 17:20
I had opened a case with Jamf regarding this, and just heard back that a Product Issue has been filed pertaining to the issue we have seen. Jamf Product Issue: PI-007800 "macOS Self Service - Fails to restart macOS 10.13 device". You might want to reach out to your Jamf Support person and mention this is affecting you as well.

**Comment by mpermann** [comment] 2019-12-20 17:41
@jrouthier have you tried doing an upgrade from Mojave to Catalina? I'm curious if the failure to restart issue will also present itself when performing that workflow. I've not had a chance to test that yet. But we'll be doing mass Catalina upgrades from Mojave starting in March or April of next year. Testing the workflow for 10.14.6 to 10.15.x is on my list after I come back from winter break.

**Comment by jrouthier** [comment] 2020-01-14 13:17
@mpermann I have not tried with Catalina yet, that is on my docket to test in the next month or two (working through Mojave upgrades right now).

**Comment by mpermann** [comment] 2020-01-23 22:36
@jrouthier I finally got around to testing the workflow with Catalina. I added the `killall Self\ Service` to the script and it worked for Catalina. Prior to adding that it did get stuck because Self Service wouldn't quit.  So clearly PI-007800 extends beyond just macOS 10.13. It probably affects any OS upgrade using this workflow. It really seems like they messed something up in Self Service app that is causing this issue.

**Comment by nstrauss** [comment] 2020-01-24 15:31
I think `--forcequitapps` is the better solution here. I've tested with Catalina installers and it does what it says on the tin. Kills all open processes and restarts.

**Comment by samuel-harvey** [comment] 2020-02-27 05:54
> I think `--forcequitapps` is the better solution here. I've tested with Catalina installers and it does what it says on the tin. Kills all open processes and restarts.

Would you mind sharing your code? I'm having trouble with getting the script to work from Mojave>Catalina. Also, are you using a pkg'd installer as show in the readme? 

Thanks in advance :)

**Comment by taniguti** [comment] 2020-11-24 13:32
Fixed by #140

**Closed by taniguti** 2020-11-24 13:32 UTC
